"""Instructions:
<> Big O: O(n^2)
In this task, you are required to implement a function called print_items(n).

This function takes one integer argument, n, and prints out a pair of numbers 
(i, j) for every possible combination of i and j in the range of 0 
up to but not including n.

Each pair (i, j) is printed on a new line. i and j iterate over the range 
independently, so every combination of i and j in the range should be printed.

The output of the function should be a series of pairs, printed one after the 
other, each on a new line. The pairs should be printed in the order that 
they are generated by the nested loops.

Here's an example output for print_items(3):
0 0
0 1
0 2
1 0
1 1
1 2
2 0
2 1
2 2


The pairs are generated by the nested loops, with i taking on every value from 
0 to n - 1 in the outer loop, and j taking on every value from 0 to n - 1 in 
the inner loop for each value of i.

Remember, the goal of this function is to print all the pairs (i, j) where 
i and j are in the range of 0 up to n - 1.
"""


"""Pseudocode:
a) Define a function print_items that takes an integer input n

b) Initialize the first loop with i from 0 to n-1:

    b.1) For each i in the first loop, initialize the second loop with j from 0 to n-1:

    b.1.1) For each j in the second loop, print the pair of i and j

c) End function when all pairs (i, j) have been printed
"""

def print_items(n):
    """This function uses a nested loop to iterate over all combinations
    of integers from 0 up to, but not including, n. For each pair,
    it prints the values of i and j."""
    for i in range(n):
        """Main loop"""
        for j in range(n):
            """Nested loop"""
            print(i,j)
            
print_items(10)